name: Jest Coverage Comment
on:
  pull_request:
jobs:
  build:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: |
          yarn run test:ui:coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main