name: Jest Test Coverage
on:
  pull_request:
jobs:
  build:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: |
          yarn run test:ui:coverage
    
        #Comments the JEST tests in the PR
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
        #Comments the JEST tests diff in the PR
      - name: Jest Coverage Comment Diff
        id: testCoverage
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
            fullCoverageDiff: false
            runCommand: "yarn jest --collectCoverageFrom='[\"src/**/*.{js,jsx,ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit --detectOpenHandles"
            delta: 0.5
      
      # Jest Test Coverage Threshold
      - name: Jest Coverage Comment
        uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80